export const PRODUCT_lIST_REQUEST = 'PRODUCT_lIST_REQUEST'
export const PRODUCT_LIST_SUCCESS = 'PRODUCT_lIST_SUCCESS'
export const PRODUCT_lIST_FAIL = 'PRODUCT_lIST_FAIL'

export const PRODUCT_DETAILS_REQUEST = 'PRODUCT_DETAILS_REQUEST'
export const PRODUCT_DETAILS_SUCCESS = 'PRODUCT_DETAILS_SUCCESS'
export const PRODUCT_DETAILS_FAIL = 'PRODUCT_DETAILS_FAIL'



export const PRODUCT_DETAILS_FAIL1 = 'PRODUCT_DETAILS_FAIL1'
export const PRODUCT_DETAILS_FAIL2 = 'PRODUCT_DETAILS_FAIL1'

